name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: sreelakshmig009/github-activity-readme@main
        env:
          GITHUB_TOKEN: ${{ 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 }}
